export const offerSummeryList = [
    {
        "Item": 10,
        "Plant": "Automotive",
        "Material_Number": 25648,
        "BOM": ".div",
        "BOM_Width": "-0.10/+0.10",
        "Material_Format": "1/3 ins",
        "Thickness": "150/1180",
        "Width": "s253JR",
        "Length": "180.G",
        "Axis": "HRP",
        "Applicable_PGL_Base_Price": 315,
        "Total_Mill_Extra": 4200,
        "Total_Processing_Extra": 0,
        "Total_Transport_Extra": 1420,
        "Total_Effective_Extra": 45,
        "Proposed_Price": 1,
        "Volume_Offered_In_Tonnes": 30,
        "PCR_Price": 20,
        "Gap_With_Applicable_PGL_Base_Price": 10
    },
    {
        "Item": 10,
        "Plant": "Automotive",
        "Material_Number": 25648,
        "BOM": ".div",
        "BOM_Width": "-0.10/+0.10",
        "Material_Format": "1/3 ins",
        "Thickness": "150/1180",
        "Width": "s253JR",
        "Length": "180.G",
        "Axis": "HRP",
        "Applicable_PGL_Base_Price": 315,
        "Total_Mill_Extra": 4200,
        "Total_Processing_Extra": 0,
        "Total_Transport_Extra": 1420,
        "Total_Effective_Extra": 45,
        "Proposed_Price": 1,
        "Volume_Offered_In_Tonnes": 30,
        "PCR_Price": 20,
        "Gap_With_Applicable_PGL_Base_Price": 10
    },
    {
        "Item": 10,
        "Plant": "Automotive",
        "Material_Number": 25648,
        "BOM": ".div",
        "BOM_Width": "-0.10/+0.10",
        "Material_Format": "1/3 ins",
        "Thickness": "150/1180",
        "Width": "s253JR",
        "Length": "180.G",
        "Axis": "HRP",
        "Applicable_PGL_Base_Price": 315,
        "Total_Mill_Extra": 4200,
        "Total_Processing_Extra": 0,
        "Total_Transport_Extra": 1420,
        "Total_Effective_Extra": 45,
        "Proposed_Price": 1,
        "Volume_Offered_In_Tonnes": 30,
        "PCR_Price": 20,
        "Gap_With_Applicable_PGL_Base_Price": 10
    }
]
