export interface offerSummery {
    'Item': any,
    'Plant': any,
    'Material_Number': any, 
    'Applicable_PGL_Base_Price': any,
    'Total_mill_Extra': any,
    'Total_Processing_Extra': any,
    'Total_Transport_Extra': any,
    'Total_Effective_Extra': any,
    'Proposed_Price': any,
    'Volume_Offered_In_Tonnes': any,
    'PCR_Price': any,
    'Gap_With_Applicable_PGL_Base_Price': any
}

export interface customerProduct {
    'HR': any,
    'CR': any,
    'GALV': any,
    'EZN': any,
    'ZM': any,
    'OTH': any
}
export interface customerInvoiceQuantity {
    'Invoiced_Quantity_1': any,
    'Invoiced_Quantity_2': any,
    'Invoiced_Quantity_3': any
}
export interface customerShape {
    'Slit': any,
    'Sheets': any,
    'blanks': any
}
export interface  materialCharacteristics{
    "material":any,
    "plant":any,
    "bOM":any,
    "bOMWidth":any,
    "grade":any,
    "materialFormat":any,
    "thickness":any,
    "width":any,
    "Length":any,
    "axis":any,
    "bundleWeight":any,
    "minkg/MM":any,
    "weightperpiece":any,
    "articlesSSPSteelGradeCodeA2C":any,
    "qualityFamily":any,
    "surfaceFinish":any,
    "oiling":any,
    "packaing":any,
    "transport":any,
    "coating":any,
    "Epassivation":any,
    "surfaceaspect":any,
    "surfaceaspectstandardId":any,
    "Roughness":any,
    "RoughnessstandardId":any,
    "Ramaxtopside":any,
    "Ramaxbottomside":any,
    "RaminTopside":any,
    "Raminbottomside":any,
    "metalliccoating":any,
    "metalliccoatingstandardId":any,
    "metalliccoatingfinish":any,
    "metalliccoatingside":any,
    "oilingquantityrange":any,
    "Kindofoil1":any,
    "protectionSD":any,
    "thicknesstolerancestdId":any,
    "thicknesstoleranceseverity":any,
    "widthtolerancestdId":any,
    "edgetrimmedlasttool":any,
    "widthtoleranceseverity":any,
    "pickledwelds":any,
    "eUorigin":any,
    "nominalinnerdiameter":any,
    "calculatedweightpcemin":any,
    "calculatedweightpcemax":any,
    "outerdiametermin":any,
    "outerdiametermax":any,
    "weight/mmmin":any,
    "weight/mmmax":any,
    "purchasepackagingcode":any,
    "bundlegrossweightmaxkg":any,
    "woodenspacer":any,
    "packaginginstruction4":any,
    "foilprotection":any,
    "packaginginstruction2":any,
    "Hard protection":any,
    "specialcase":any,
    "packaginginstruction1":any,
    "woodentype":any,
    "paletfixing":any,
    "soldtoarticlenumber":any,
    "invoicedweight":any,
    "invoiceunit":any,
}